[web]
web-0 ansible_host=178.154.226.86 fqdn=fhm696a4m2c06i2g7gtr.auto.internal
web-1 ansible_host=158.160.118.202 fqdn=fhma0ohdn9p9gqmfm318.auto.internal

[db]
main ansible_host=178.154.240.29 fqdn=fhmso1bgkambif326nac.auto.internal
replica ansible_host=158.160.119.93 fqdn=fhmaamcnn6dgtvd3a5uu.auto.internal

[storage]
storage ansible_host=158.160.45.59 fqdn=fhm1markivch31201udn.auto.internal
