apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-for-nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Ставь лайк</title>
    </head>
    <body>
      <h1>Если любишь маму</h1>
    </body>
    </html>