apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}
spec:
  ports:
  - name: {{ .Values.deployment.image.container1 }}
    port: {{ .Values.service.ports.port1 }}
    protocol: TCP
    targetPort: {{ .Values.service.ports.targetPort1 }}
  - name: {{ .Values.deployment.image.container2name }}
    port: {{ .Values.service.ports.port2 }}
    protocol: TCP
    targetPort: {{ .Values.service.ports.targetPort2 }}
  selector:
    app: {{ .Values.labels.app }}